/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandComponent: typeof import('./src/components/brands/BrandComponent.vue')['default']
    BrandsComponent: typeof import('./src/components/brands/BrandsComponent.vue')['default']
    BrandSelectorComponent: typeof import('./src/components/brands/BrandSelectorComponent.vue')['default']
    CarouselComponent: typeof import('./src/components/CarouselComponent.vue')['default']
    CartActionsButton: typeof import('./src/components/cart/CartActionsButton.vue')['default']
    CartActionsButtonComponent: typeof import('./src/components/cart/CartActionsButtonComponent.vue')['default']
    CartOffCanvasBodyComponent: typeof import('./src/components/cart/CartOffCanvasBodyComponent.vue')['default']
    CategoriesComponent: typeof import('./src/components/categories/CategoriesComponent.vue')['default']
    CategoryComponent: typeof import('./src/components/categories/CategoryComponent.vue')['default']
    CategorySelectorComponent: typeof import('./src/components/categories/CategorySelectorComponent.vue')['default']
    CouponBannerComponent: typeof import('./src/components/CouponBannerComponent.vue')['default']
    CustomBreadCrumbComponent: typeof import('./src/components/CustomBreadCrumbComponent.vue')['default']
    CustomFooterComponent: typeof import('./src/components/CustomFooterComponent.vue')['default']
    CustomNavBarComponent: typeof import('./src/components/CustomNavBarComponent.vue')['default']
    DynamicHeightDivComponent: typeof import('./src/components/utils/DynamicHeightDivComponent.vue')['default']
    ElementComponent: typeof import('./src/components/utils/ElementComponent.vue')['default']
    FacebookIcon: typeof import('./src/components/icons/FacebookIcon.vue')['default']
    IconWithNotificationComponent: typeof import('./src/components/utils/IconWithNotificationComponent.vue')['default']
    InstagramIcon: typeof import('./src/components/icons/InstagramIcon.vue')['default']
    ItemComponent: typeof import('./src/components/items/ItemComponent.vue')['default']
    ItemsComponent: typeof import('./src/components/items/ItemsComponent.vue')['default']
    OffCanvasBodyCartComponent: typeof import('./src/components/cart/OffCanvasBodyCartComponent.vue')['default']
    OffCanvasBodyControlPanelComponent: typeof import('./src/components/users/OffCanvasBodyControlPanelComponent.vue')['default']
    OffCanvasComponent: typeof import('./src/components/OffCanvasComponent.vue')['default']
    RatingComponent: typeof import('./src/components/RatingComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialsComponent: typeof import('./src/components/SocialsComponent.vue')['default']
    TwitterIcon: typeof import('./src/components/icons/TwitterIcon.vue')['default']
    TwitterXIcon: typeof import('./src/components/icons/TwitterXIcon.vue')['default']
    UserControlPanelOffCanvasBodyComponent: typeof import('./src/components/users/UserControlPanelOffCanvasBodyComponent.vue')['default']
  }
}
