/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarouselComponent: typeof import('./src/components/CarouselComponent.vue')['default']
    CustomBreadCrumbComponent: typeof import('./src/components/CustomBreadCrumbComponent.vue')['default']
    CustomFooterComponent: typeof import('./src/components/CustomFooterComponent.vue')['default']
    CustomNavBarComponent: typeof import('./src/components/CustomNavBarComponent.vue')['default']
    DynamicHeightDivComponent: typeof import('./src/components/utils/DynamicHeightDivComponent.vue')['default']
    FacebookIcon: typeof import('./src/components/icons/FacebookIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconWithNotificationComponent: typeof import('./src/components/utils/IconWithNotificationComponent.vue')['default']
    InstagramIcon: typeof import('./src/components/icons/InstagramIcon.vue')['default']
    ItemComponent: typeof import('./src/components/ItemComponent.vue')['default']
    ItemDetailsComponent: typeof import('./src/components/ItemDetailsComponent.vue')['default']
    ItemListComponent: typeof import('./src/components/ItemListComponent.vue')['default']
    ItemsComponent: typeof import('./src/components/ItemsComponent.vue')['default']
    OffCanvasBodyCartComponent: typeof import('./src/components/OffCanvasBodyCartComponent.vue')['default']
    OffCanvasBodyControlPanelComponent: typeof import('./src/components/OffCanvasBodyControlPanelComponent.vue')['default']
    OffCanvasComponent: typeof import('./src/components/OffCanvasComponent.vue')['default']
    RatingComponent: typeof import('./src/components/RatingComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialComponent: typeof import('./src/components/SocialComponent.vue')['default']
    SocialsComponent: typeof import('./src/components/SocialsComponent.vue')['default']
    TwitterIcon: typeof import('./src/components/icons/TwitterIcon.vue')['default']
    TwitterXIcon: typeof import('./src/components/icons/TwitterXIcon.vue')['default']
  }
}
