version: '3.8'

services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: clockdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PracticaRoot
      MYSQL_DATABASE: clockdb
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  # Aplicación Spring Boot usando .jar pre-compilado
  backend:
    image: openjdk:21-jdk-slim
    container_name: spring-backend
    depends_on:
      - db
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clockdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: PracticaRoot
    volumes:
      - ./backend/target/backend-0.0.1-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge
