version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: clockdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PracticaRoot
      MYSQL_DATABASE: clockdb  
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge