version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: clockdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PracticaRoot
      MYSQL_DATABASE: clockdb
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - clock-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: spring-backend
    depends_on:
      - db
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clockdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: PracticaRoot
    networks:
      - clock-network

  frontend:
    image: nginx:alpine
    container_name: vue-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - clock-network

volumes:
  mysql_data:

networks:
  clock-network:
    driver: bridge
