services:
  db:
    image: mysql:8.0
    container_name: clockdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PracticaRoot
      MYSQL_DATABASE: clockdb
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - clock-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  clock-backend:  
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clock-backend  
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clockdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: PracticaRoot
    networks:
      - clock-network

  clock-frontend:  
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clock-frontend 
    ports:
      - "80:80"
    depends_on:
      - clock-backend  
    networks:
      - clock-network

volumes:
  mysql_data:

networks:
  clock-network:
    driver: bridge