spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/clockdb
    username: root
    password: PracticaRoot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

##Configuración de logging detallado
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        http: DEBUG
        security: DEBUG
    com:
      fasterxml:
        jackson: DEBUG
    com.ecommercevcs: DEBUG  # Ajusta esto a tu paquete base
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"