spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3305/clockdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:PracticaRoot}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: carlosrose96@gmail.com
    password: ejqh kwht qsyx wokh
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# Configuración de logging detallado
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        http: DEBUG
        security: DEBUG
    com:
      fasterxml:
        jackson: DEBUG
      ecommercevcs: DEBUG  # Ajusta esto a tu paquete base si es otro
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
