spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/clockdb
    username: root
    password: PracticaRoot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update    
    show-sql: true