spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3305/clockdb?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:PracticaRoot}
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: 60000
    maximum-pool-size: 10
    minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: clockandcrownvcs@gmail.com
    password: ilut iuvd bglo kgfz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        http: DEBUG
        security: DEBUG
        jdbc: DEBUG
    com:
      fasterxml:
        jackson: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"